[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:php-fpm]
command=php-fpm -F
autorestart=true

[program:nginx]
command=nginx -g 'daemon off;'
autorestart=true

[program:laravel-mqtt]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan app:mqtt-subscriber
autostart=true
autorestart=true
stopasgroup=true
user=www-data
numprocs=1 
redirect_stderr=true
stdout_logfile=/var/log/supervisor/laravel-mqtt.log
stderr_logfile=/var/log/supervisor/laravel-mqtt_err.log 

[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1                  ; Puedes subir esto si tienes mucho tráfico
redirect_stderr=true
stdout_logfile=/var/log/supervisor/worker.log